/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import bean.User;
import dao.UserDao;
import javax.swing.JOptionPane;

/**
 *
 * @author ESIC
 */
public class Connexion extends javax.swing.JFrame {

    /**
     * Creates new form Connexion
     */
    public Connexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.JPanel();
        lbTitre = new javax.swing.JLabel();
        lbSousTitre = new javax.swing.JLabel();
        bg2 = new javax.swing.JPanel();
        lbLogin = new javax.swing.JLabel();
        lbMdp = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtMdp = new javax.swing.JPasswordField();
        butConnexion = new javax.swing.JButton();
        butInscription = new javax.swing.JButton();
        lbPasEncore = new javax.swing.JLabel();
        lbError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg1.setBackground(new java.awt.Color(73, 73, 255));
        bg1.setForeground(new java.awt.Color(113, 122, 190));

        lbTitre.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbTitre.setForeground(new java.awt.Color(255, 255, 255));
        lbTitre.setText("Bienvenue sur APoidsPlication");

        lbSousTitre.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lbSousTitre.setForeground(new java.awt.Color(255, 255, 255));
        lbSousTitre.setText("L'application qui vous veut du bien");

        javax.swing.GroupLayout bg1Layout = new javax.swing.GroupLayout(bg1);
        bg1.setLayout(bg1Layout);
        bg1Layout.setHorizontalGroup(
            bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg1Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg1Layout.createSequentialGroup()
                        .addComponent(lbTitre)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg1Layout.createSequentialGroup()
                        .addComponent(lbSousTitre)
                        .addGap(325, 325, 325))))
        );
        bg1Layout.setVerticalGroup(
            bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbTitre)
                .addGap(18, 18, 18)
                .addComponent(lbSousTitre)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        bg2.setBackground(new java.awt.Color(204, 206, 224));

        lbLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(0, 0, 0));
        lbLogin.setText("Login");

        lbMdp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMdp.setForeground(new java.awt.Color(0, 0, 0));
        lbMdp.setText("Mot de passe");

        txtLogin.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtMdp.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        butConnexion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        butConnexion.setText("Connexion");
        butConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConnexionActionPerformed(evt);
            }
        });

        butInscription.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        butInscription.setText("Inscription");
        butInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInscriptionActionPerformed(evt);
            }
        });

        lbPasEncore.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        lbPasEncore.setForeground(new java.awt.Color(51, 51, 51));
        lbPasEncore.setText("Pas encore inscrit ?");

        lbError.setBackground(new java.awt.Color(204, 206, 224));
        lbError.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        lbError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(butInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbPasEncore, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(butConnexion))
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLogin)
                            .addComponent(lbMdp))
                        .addGap(52, 52, 52)
                        .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMdp, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(txtLogin)))
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMdp)
                    .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(butConnexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPasEncore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butInscription)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bg2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConnexionActionPerformed
        User u;
        String login = txtLogin.getText();
        char [] c = txtMdp.getPassword();
        String mdp = new String(c);
        
        try {
            u = UserDao.getByLoginPass(login, mdp);
            
            if (u != null){
            Profile p = new Profile(u);
            p.setVisible(true);
            this.setVisible(false);
        }
        else{
            lbError.setText("Login ou Mot de passe érroné");
            
        }
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_butConnexionActionPerformed

    private void butInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInscriptionActionPerformed
        Inscription i = new Inscription();
        i.setVisible(true);
    }//GEN-LAST:event_butInscriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Connexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg1;
    private javax.swing.JPanel bg2;
    private javax.swing.JButton butConnexion;
    private javax.swing.JButton butInscription;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbMdp;
    private javax.swing.JLabel lbPasEncore;
    private javax.swing.JLabel lbSousTitre;
    private javax.swing.JLabel lbTitre;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtMdp;
    // End of variables declaration//GEN-END:variables
}
