/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static ihm.Profile.u;

/**
 *
 * @author stagiaire
 */
public class Magic extends javax.swing.JFrame {

    /**
     * Creates new form Magic
     */
    public Magic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtValider = new javax.swing.JButton();
        Msg = new javax.swing.JLabel();
        txtRep = new javax.swing.JTextField();
        jRetour = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        Consigne = new javax.swing.JLabel();
        TitreM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 206, 204));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        BtValider.setText("Valider");
        BtValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtValiderActionPerformed(evt);
            }
        });

        Msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtRep.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtRep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRep.setBorder(null);

        jRetour.setText("Retour");
        jRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetourActionPerformed(evt);
            }
        });

        time.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        Consigne.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Consigne.setText("Devinez le nombre magic");

        TitreM.setBackground(new java.awt.Color(51, 51, 255));
        TitreM.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        TitreM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitreM.setText("Magic");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(Consigne))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(TitreM, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRetour)
                            .addComponent(BtValider)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(txtRep, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(Msg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(190, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitreM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(Consigne)
                .addGap(18, 18, 18)
                .addComponent(txtRep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BtValider)
                .addGap(18, 18, 18)
                .addComponent(jRetour)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(Msg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetourActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Merci d'avoir joué");
        Profile p = new Profile(u);
        p.setVisible(true);
       
        
    }//GEN-LAST:event_jRetourActionPerformed

    private void BtValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtValiderActionPerformed
        // TODO add your handling code here:
        rep = Integer.parseInt(txtRep.getText());
         txtRep.setText("");
        // System.out.println("rep = " + rep);

        
        if (nb <= 0) { 
                timer.stop();
                but = 60;
                nb = but;
                JOptionPane.showMessageDialog(null, "Temps écoulé, retour au début !");
                gener();
                timer.restart();
                
        }
                
        if ( rep != nombre){
            
            if (rep < nombre){
            Msg.setText("Plus grand !");
            
            }
            if (rep > nombre){
            Msg.setText("Plus petit !");
            }
            //if (nb <= 0) { 
             //   JOptionPane.showMessageDialog(null, "Temps écoulé");
            //}
        
        }
        
        if (rep == nombre){
            Msg.setText("Trouvé !");
            gener();
            timer.stop();
            but-= 5;
            nb = but;
            timer.restart();
        }
    }//GEN-LAST:event_BtValiderActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        gener();
        timer();

    }//GEN-LAST:event_formWindowOpened

    int nombre;
    int rep;
    Timer timer;
    int but = 60;
    int nb = but;
    int a = 0;
    
   
    
    public void gener(){
        nombre = (int)(Math.random()*30) ;
        System.out.println(nombre);
    }
         
    
    
    private void timer(){
        timer = new Timer(1000, new ActionListener() {
        @Override
        
        public void actionPerformed(ActionEvent e) {
        time.setText(String.valueOf(nb) + " s");
        nb--;
        }
        });
        timer.start();
        }
           
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Magic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Magic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Magic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Magic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Magic().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtValider;
    private javax.swing.JLabel Consigne;
    private javax.swing.JLabel Msg;
    private javax.swing.JLabel TitreM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jRetour;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtRep;
    // End of variables declaration//GEN-END:variables
}
